In [1]:
#WORKING NOTEBOOK FOR MINI-PROJECT 1 (HEBER) 6 FEB 2019
from __future__ import print_function
import pandas as pd
import numpy as np

df = pd.read_csv('C:/Users/Admin/Documents/DATA SCIENCE/Data Sets/Chile_earthquake/Chilean_Earthquake_Binary_data.csv')
#drop "Clinic_ID" and "Excel_File_ID" from dataframe
df.drop('Clinic_ID', axis=1, inplace=True, errors='ignore')
df.drop('Excel_File_ID', axis=1, inplace=True, errors='ignore')


#identify records with missing values
#display(df.iloc[df['Parity'].isna().get_values(),:].transpose() \
#           .style.highlight_null(null_color='red'))

#replace NaN in Parity with 0, which is the most common label
df['Parity'].fillna(0, inplace=True)

print('Summary Statistics for Initial Variables')
display(df.describe())



Summary Statistics for Initial Variables


Day        Month         Year          Sex       Weight  \
count  4076.000000  4076.000000  4076.000000  4076.000000  4076.000000   
mean     15.374141     7.113837  2009.517664     0.512022  3355.048086   
std       8.736868     2.762731     0.499749     0.499917   384.896728   
min       1.000000     2.000000  2009.000000     0.000000  1790.000000   
25%       8.000000     5.000000  2009.000000     0.000000  3098.750000   
50%      15.000000     7.000000  2010.000000     1.000000  3345.000000   
75%      23.000000    10.000000  2010.000000     1.000000  3610.000000   
max      31.000000    12.000000  2010.000000     1.000000  4890.000000   

            Length    Head_circ      apgar_1      apgar_5  Municipality  \
count  4076.000000  4076.000000  4076.000000  4076.000000   4076.000000   
mean     49.696516    34.689463     8.767664     9.363837      1.480128   
std       1.723517     1.187216     0.730237     0.521778      0.638901   
min      40.000000    29.000000     2.000000     6.000000      0.000000   
25%      48.500000    34.000000     9.000000     9.000000      1.000000   
50%      50.000000    35.000000     9.000000     9.000000      2.000000   
75%      51.000000    35.500000     9.000000    10.000000      2.000000   
max      56.000000    40.000000    10.000000    10.000000      2.000000   

       Wgt_for_age     Gest_age    Trimester  Low_birthwgt    Premature  \
count  4076.000000  4076.000000  4076.000000   4076.000000  4076.000000   
mean      0.167566    38.802993     1.999755      0.013248     0.028214   
std       0.481448     1.074730     0.820145      0.114350     0.165604   
min       0.000000    34.000000     1.000000      0.000000     0.000000   
25%       0.000000    38.000000     1.000000      0.000000     0.000000   
50%       0.000000    39.000000     2.000000      0.000000     0.000000   
75%       0.000000    40.000000     3.000000      0.000000     0.000000   
max       2.000000    41.000000     3.000000      1.000000     1.000000   

       Maternal_age       Parity   Trim_study  Ponderal_index      Exposed  
count   4076.000000  4076.000000  4076.000000     4076.000000  4076.000000  
mean      27.839794     0.611138     3.552748        2.729498     0.517664  
std        5.380683     0.782109     1.677835        0.228661     0.499749  
min       14.000000     0.000000     1.000000        1.696000     0.000000  
25%       24.000000     0.000000     2.000000        2.579992     0.000000  
50%       28.000000     0.000000     4.000000        2.717342     1.000000  
75%       31.000000     1.000000     5.000000        2.866327     1.000000  
max       44.000000     5.000000     6.000000        5.283747     1.000000

In [2]:
#ignore some columns
columns_ignore = ['Day', 'Month', 'Year']
df_lite = df.drop(columns_ignore, axis=1)


In [3]:

#map some categorical variables to work with parallel coordinate plots and have a more natural ordering
df_lite['Sex'] = df_lite['Sex'].map({'female': 0, 'male': 1})
df_lite['Premature'] = df_lite['Premature'].map({'Premature': 1, 'Not premature': 0})
df_lite['Trim_study'] = df_lite['Trim_study'].map({'First2009': '1', 'Second2009': '2', 'Third2009': '3', 
                          'First2010': '4', 'Second2010': '5', 'Third2010': '6' })


In [4]:

#get list of categorical variables
categories = list(df_lite.columns[df_lite.dtypes == 'object']) \
                    + ['Parity', 'apgar_1', 'apgar_5', 'Exposed', 'Sex', 'Premature', 'Trim_study', 'Gest_age']
continuous = [col for col in df_lite.columns if col not in categories]


In [5]:
#confirm list of categorical variables
print('Categorical variables: {}\n'.format(categories))
print('Continuous variables: {}\n'.format(continuous))

Categorical variables: ['Trim_study', 'Parity', 'apgar_1', 'apgar_5', 'Exposed', 'Sex', 'Premature', 'Trim_study', 'Gest_age']

Continuous variables: ['Weight', 'Length', 'Head_circ', 'Municipality', 'Wgt_for_age', 'Trimester', 'Low_birthwgt', 'Maternal_age', 'Ponderal_index']



In [6]:
## WHEN THIS BLOCK RUNS QUICKLY GET DEAD KERNAL. SKIPPING THIS BLOCK.
#change data type for categorical variables to pandas 'category' type
#df_lite[categories] = df_lite[categories].astype('category')


In [7]:
df_lite.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4076 entries, 0 to 4075
Data columns (total 17 columns):
Sex               0 non-null float64
Weight            4076 non-null int64
Length            4076 non-null float64
Head_circ         4076 non-null float64
apgar_1           4076 non-null int64
apgar_5           4076 non-null int64
Municipality      4076 non-null int64
Wgt_for_age       4076 non-null int64
Gest_age          4076 non-null int64
Trimester         4076 non-null int64
Low_birthwgt      4076 non-null int64
Premature         0 non-null float64
Maternal_age      4076 non-null int64
Parity            4076 non-null float64
Trim_study        0 non-null object
Ponderal_index    4076 non-null float64
Exposed           4076 non-null int64
dtypes: float64(6), int64(10), object(1)
memory usage: 541.4+ KB


In [8]:
print('Summary Statistics for Initial Variables')
display(df_lite.describe())


Summary Statistics for Initial Variables


Sex       Weight       Length    Head_circ      apgar_1      apgar_5  \
count  0.0  4076.000000  4076.000000  4076.000000  4076.000000  4076.000000   
mean   NaN  3355.048086    49.696516    34.689463     8.767664     9.363837   
std    NaN   384.896728     1.723517     1.187216     0.730237     0.521778   
min    NaN  1790.000000    40.000000    29.000000     2.000000     6.000000   
25%    NaN  3098.750000    48.500000    34.000000     9.000000     9.000000   
50%    NaN  3345.000000    50.000000    35.000000     9.000000     9.000000   
75%    NaN  3610.000000    51.000000    35.500000     9.000000    10.000000   
max    NaN  4890.000000    56.000000    40.000000    10.000000    10.000000   

       Municipality  Wgt_for_age     Gest_age    Trimester  Low_birthwgt  \
count   4076.000000  4076.000000  4076.000000  4076.000000   4076.000000   
mean       1.480128     0.167566    38.802993     1.999755      0.013248   
std        0.638901     0.481448     1.074730     0.820145      0.114350   
min        0.000000     0.000000    34.000000     1.000000      0.000000   
25%        1.000000     0.000000    38.000000     1.000000      0.000000   
50%        2.000000     0.000000    39.000000     2.000000      0.000000   
75%        2.000000     0.000000    40.000000     3.000000      0.000000   
max        2.000000     2.000000    41.000000     3.000000      1.000000   

       Premature  Maternal_age       Parity  Ponderal_index      Exposed  
count        0.0   4076.000000  4076.000000     4076.000000  4076.000000  
mean         NaN     27.839794     0.611138        2.729498     0.517664  
std          NaN      5.380683     0.782109        0.228661     0.499749  
min          NaN     14.000000     0.000000        1.696000     0.000000  
25%          NaN     24.000000     0.000000        2.579992     0.000000  
50%          NaN     28.000000     0.000000        2.717342     1.000000  
75%          NaN     31.000000     1.000000        2.866327     1.000000  
max          NaN     44.000000     5.000000        5.283747     1.000000

In [14]:
## PROBLEM. Variables Sex, Premature, and Trim_study are all filled now with NaN.
## This happened in cell 3 with mapping "to replace text with numbers". But they were already numbers.
## so Remap eliminated all data.
## Replace with original data.

df_newlite = df_lite
df_newlite['Sex'] = df['Sex']
df_newlite['Premature'] = df['Premature']
df_newlite['Trim_study'] = df['Trim_study']

df_newlite.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4076 entries, 0 to 4075
Data columns (total 17 columns):
Sex               4076 non-null int64
Weight            4076 non-null int64
Length            4076 non-null float64
Head_circ         4076 non-null float64
apgar_1           4076 non-null int64
apgar_5           4076 non-null int64
Municipality      4076 non-null int64
Wgt_for_age       4076 non-null int64
Gest_age          4076 non-null int64
Trimester         4076 non-null int64
Low_birthwgt      4076 non-null int64
Premature         4076 non-null int64
Maternal_age      4076 non-null int64
Parity            4076 non-null float64
Trim_study        4076 non-null int64
Ponderal_index    4076 non-null float64
Exposed           4076 non-null int64
dtypes: float64(4), int64(13)
memory usage: 541.4 KB


In [ ]:
## TRAINING AND TESTING

In [15]:
from sklearn.model_selection import ShuffleSplit

# predict the X and y data:
if 'Ponderal_index' in df_newlite:
    y = df_newlite['Exposed'].values # get the labels we want
    del df_newlite['Exposed'] # get rid of the class label
    X = df_newlite.values # use everything else to predict!

    ## X and y are now numpy matrices, by calling 'values' on the pandas data frames we
    #    have converted them into simple matrices to use with scikit learn
    
    
# to use the cross validation object in scikit learn, we need to grab an instance
#    of the object and set it up. This object will be able to split our data into 
#    training and testing splits
num_cv_iterations = 3
num_instances = len(y)
cv_object = ShuffleSplit(n_splits=num_cv_iterations,
                         test_size  = 0.2)
                         
print(cv_object)

ShuffleSplit(n_splits=3, random_state=None, test_size=0.2, train_size=None)


In [ ]:
## LOGISTIC REGRESSION

In [16]:
# run logistic regression and vary some parameters
from sklearn.linear_model import LogisticRegression
from sklearn import metrics as mt

# Create a reusable logisitic regression object
# Set up the object with different learning parameters and constants
lr_clf = LogisticRegression(penalty='l2', C=1.0, class_weight=None) # This is the object

# Use the cv_object that we set up before to iterate through the 
#    different training and testing sets. Each time reuse the logisitic regression 
#    object, but train it on different data each time it is used.
# Every time the following code is run
#   it randomly creates a new training and testing set, 
#   so accuracy will be different each time

iter_num=0
# the indices are the rows used for training and testing in each iteration
for train_indices, test_indices in cv_object.split(X,y): 
    # Create new variables 
    X_train = X[train_indices]
    y_train = y[train_indices]
    
    X_test = X[test_indices]
    y_test = y[test_indices]
    
    # train the reusable logisitc regression model on the training data
    lr_clf.fit(X_train,y_train)  # train object
    y_hat = lr_clf.predict(X_test) # get test set predictions

    # Get the accuracy and confusion matrix for this iterations of training/testing
    acc = mt.accuracy_score(y_test,y_hat)
    conf = mt.confusion_matrix(y_test,y_hat)
    print("====Iteration",iter_num," ====")
    print("accuracy", acc )
    print("confusion matrix\n",conf)
    iter_num+=1
    
## AS SEEN IN THE OUTPUT, THIS IS TOO ACCURATE, WITH VALUES OF 1.0

====Iteration 0  ====
accuracy 1.0
confusion matrix
 [[401   0]
 [  0 415]]
====Iteration 1  ====
accuracy 1.0
confusion matrix
 [[409   0]
 [  0 407]]
====Iteration 2  ====
accuracy 1.0
confusion matrix
 [[384   0]
 [  0 432]]


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [17]:
## Redo the Logistic Regression using the other two code chunks we were given (more compact code).
## Expect similar output as above (matrices will of course be slightly different)

## Chunk #2 - intermediate compactness
for iter_num, (train_indices, test_indices) in enumerate(cv_object.split(X,y)):
    lr_clf.fit(X[train_indices],y[train_indices])  # train object
    y_hat = lr_clf.predict(X[test_indices]) # get test set precitions

    # print the accuracy and confusion matrix 
    print("====Iteration",iter_num," ====")
    print("accuracy", mt.accuracy_score(y[test_indices],y_hat)) 
    print("confusion matrix\n",mt.confusion_matrix(y[test_indices],y_hat))

## AS SEEN IN THE OUTPUT, THIS IS TOO ACCURATE, WITH VALUES OF 1.0

====Iteration 0  ====
accuracy 1.0
confusion matrix
 [[383   0]
 [  0 433]]
====Iteration 1  ====
accuracy 1.0
confusion matrix
 [[396   0]
 [  0 420]]
====Iteration 2  ====
accuracy 1.0
confusion matrix
 [[392   0]
 [  0 424]]


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [18]:
## Chunk #3 - very compact
## Apparently this also can help with parallelism
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(lr_clf, X, y=y, cv=cv_object) 
print(accuracies)

## AS SEEN IN THE OUTPUT, THIS IS TOO ACCURATE, WITH VALUES OF 1.0

[1. 1. 1.]


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
